### ISSUE TITLE
Server cannot Delete costumers created by mobile application.

### ISSUE THREAD

**Issue by samueltcsantos** [pablovfds/tyt-mobile#4]
- When you try remove a costumer account the id inside the object is not found in database.
- I have tested locally and the method to remove the costumer is Ok, The server locate the costumer and remove it. But when the mobile application is creating a costumer, the server cannot found the costumer.
- Probably the application is changing the ID. 
- Needed fix!

![bug-mobile](https://user-images.githubusercontent.com/3028970/27996935-9d7dbb22-64c3-11e7-8164-c60d17e96073.JPG)

**Comment by samueltcsantos** [comment]
Fixed! Checkout for more details.

https://bitbucket.org/ollixoteam/ollixo-server/commits/de4dd610159a4a93b667df6af96d74eb974877c4

**Comment by samueltcsantos** [comment]
Closed after bug fixed!

**Comment by pablovfds** [comment]
ok
